### ISSUE TITLE
Фидбек на домашку №2

### ISSUE THREAD

**Issue by tiny-kottan** [scorpioRED/kottans-js-2016#4]
Readme
`"npmt start"` -> `"npm start"`
package.json - doesn't contain posthtml (can automatically add it by running `npm i -S posthtml`)

`const bootstrapClsses` -> `const bootstrapClasses`
`const pat = /js-/;` - should try to get a better name

`const ifOne` -> bad name for the method. Looks more like 'removeClass'. `tmp` arg can be renamed to `allClasses`, `elClass` -> `classToRemove`
`tmp,node,elClass` -> `tmp, node, elClass` -> readability sake

`}else {` -> `} else {`

General feedback: naming is hard, but you should strive for [Self-documenting code](https://en.wikipedia.org/wiki/Self-documenting_code)

**Comment by scorpioRED** [comment]
Ok,thanks.
I changed variables to more readability and fixed README with package.json 
P.S. I tried  to add dependency by "npm i -S posthtml" , but it didn`t work because mane of the project in package.json was the same as name of module.

**Comment by sudodoki** [comment]
@scorpioRED well, that's the issue then. Rename your package then or add dependency using other syntax https://docs.npmjs.com/cli/install (like git, etc). Please, reopen this issue

**Comment by scorpioRED** [comment]
I already did it, now dependency string added in package.json. You can see it in part of this package belove:

 "dependencies": {
    "posthtml": "^0.8.7"
  }
